# Configuration File for LobbyCore!
# Made by TheRealKizu :P


# Join and Leave Message Section

# Custom Join and Leave Message Toggle
# Enables and Disables the Join and Leave Message
# Options: true | false | disable
enable-joinandleave: false

# Join Message
# Set's the specified join message!
# & - Color
# {name} - Player Name
join-message: "&bHi, &e{name}"